[package]
name = "blobs"
version = "0.0.0"
edition = "2021"
license = "MIT"
description = "NOT-Soft body physics in 2D"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.21.3"
hecs = "0.9.1"
bitflags = "1.3.2"
thunderdome = "0.6.0"
log = "0.4.17"

itertools = "0.10.5"

[target.'cfg(target_arch = "wasm32")'.dependencies]
rayon = "1.6.1"
