name: Build WASM

on:
  push:
    branches:
      - master

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-unknown-unknown

    - name: Cache rust modules
      uses: Swatinem/rust-cache@v2.0.1
      with:
        cache-on-failure: true
        shared-key: wasm

    - name: Build with cargo
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --bin demo --target wasm32-unknown-unknown --release

    - name: Prepare public folder
      run: |
        mkdir public
        cp target/wasm32-unknown-unknown/release/demo.wasm public/
        cp demo/index.html public/

    # - name: Deploy to GitHub Pages
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: ./public

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        # Upload entire repository
        path: ./public
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
